sudo: false
language: go
go:
    - 1.9.x
    - 1.8.x
    - 1.7.x
    - 1.6.x
    - 1.5.x
    - 1.4.x
before_install:
    - go get github.com/tools/godep
    - go get github.com/mattn/goveralls
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/modocache/gover
    - godep restore
    - sudo apt-get update -qq
    - sudo apt-get install -y openssl libcppunit-dev libreadline6 libreadline6-dev valgrind realpath libmodule-install-perl
    - sudo dpkg -i pkg/ubuntu/mecab-ko-all-0.996-ko-0.9.2-dic-2.0.3-20170922_Precise_Pangolin.deb
script:
    - make test
    - make coveralls
