name: go-mecab
on: ["push", "pull_request"]
jobs:
  build_and_test_on_ubuntu18:
    strategy:
      matrix:
       go: ['1.19', '1.18', '1.17', '1.16', '1.15', '1.14']
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    
    # Setup Go
    - name: Go v${{ matrix.go }} 
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }} 
    
    # Install all the dependencies
    - name: Install dependencies
      run: |
        sudo apt-get update -y -qq
        curl -ss -L -O https://github.com/torden/go-mecab/raw/develop/pkg/ubuntu/mecab-ko-all-0.996-ko-0.9.2-dic-2.1.1-20180720_Bionic_Beaver.deb
        sudo dpkg -i mecab-ko-all-0.996-ko-0.9.2-dic-2.1.1-20180720_Bionic_Beaver.deb

    # Run build of the application
    - name: Run build
      run: |
        make clean setup build
        
#    - name : Run Unittest
#      run: |
#        go test -v -test.parallel 4 -race -coverprofile=coverage.txt  -covermode=atomic
#        
#    - name: Upload coverage report
#      uses: codecov/codecov-action@v1.0.2
#      with:
#        token: 04152a42-5140-4337-b82b-c50655ada485
#        file: ./coverage.txt
#        flags: unittests
        name: go-mecab
